name: Send WhatsApp Message

on:
  schedule:
    - cron: '0 19 * * 1-5'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20' 

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -o main .

    - name: Run bot
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      run: ./main
